export const CREATE_CONTENT2_REQUEST = "CREATE_CONTENT2_REQUEST";
export const CREATE_CONTENT2_ERROR = "CREATE_CONTENT2_ERROR";
export const CREATE_CONTENT2_SUCCESS = "CREATE_CONTENT2_SUCCESS";

export const GET_CONTENT2_REQUEST = "GET_CONTENT2_REQUEST";
export const GET_CONTENT2_ERROR = "GET_CONTENT2_ERROR";
export const GET_CONTENT2_SUCCESS = "GET_CONTENT2_SUCCESS";

export const GET_SINGLE_CONTENT2_REQUEST = "GET_SINGLE_CONTENT2_REQUEST";
export const GET_SINGLE_CONTENT2_ERROR = "GET_SINGLE_CONTENT2_ERROR";
export const GET_SINGLE_CONTENT2_SUCCESS = "GET_SINGLE_CONTENT2_SUCCESS";

export const DELETE_CONTENT2_REQUEST = "DELETE_CONTENT2_REQUEST";
export const DELETE_CONTENT2_ERROR = "DELETE_CONTENT2_ERROR";
export const DELETE_CONTENT2_SUCCESS = "DELETE_CONTENT2_SUCCESS";
