export const CREATE_CONTENT3_REQUEST = "CREATE_CONTENT3_REQUEST";
export const CREATE_CONTENT3_ERROR = "CREATE_CONTENT3_ERROR";
export const CREATE_CONTENT3_SUCCESS = "CREATE_CONTENT3_SUCCESS";

export const GET_CONTENT3_REQUEST = "GET_CONTENT3_REQUEST";
export const GET_CONTENT3_ERROR = "GET_CONTENT3_ERROR";
export const GET_CONTENT3_SUCCESS = "GET_CONTENT3_SUCCESS";

export const GET_SINGLE_CONTENT3_REQUEST = "GET_SINGLE_CONTENT3_REQUEST";
export const GET_SINGLE_CONTENT3_ERROR = "GET_SINGLE_CONTENT3_ERROR";
export const GET_SINGLE_CONTENT3_SUCCESS = "GET_SINGLE_CONTENT3_SUCCESS";

export const DELETE_CONTENT3_REQUEST = "DELETE_CONTENT3_REQUEST";
export const DELETE_CONTENT3_ERROR = "DELETE_CONTENT3_ERROR";
export const DELETE_CONTENT3_SUCCESS = "DELETE_CONTENT3_SUCCESS";
