export const CREATE_DOUBT2_REQUEST = "CREATE_DOUBT2_REQUEST";
export const CREATE_DOUBT2_ERROR = "CREATE_DOUBT2_ERROR";
export const CREATE_DOUBT2_SUCCESS = "CREATE_DOUBT2_SUCCESS";

export const GET_DOUBT2_REQUEST = "GET_DOUBT2_REQUEST";
export const GET_DOUBT2_ERROR = "GET_DOUBT2_ERROR";
export const GET_DOUBT2_SUCCESS = "GET_DOUBT2_SUCCESS";

export const GET_SINGLE_DOUBT2_REQUEST = "GET_SINGLE_DOUBT2_REQUEST";
export const GET_SINGLE_DOUBT2_ERROR = "GET_SINGLE_DOUBT2_ERROR";
export const GET_SINGLE_DOUBT2_SUCCESS = "GET_SINGLE_DOUBT2_SUCCESS";

export const DELETE_DOUBT2_REQUEST = "DELETE_DOUBT2_REQUEST";
export const DELETE_DOUBT2_ERROR = "DELETE_DOUBT2_ERROR";
export const DELETE_DOUBT2_SUCCESS = "DELETE_DOUBT2_SUCCESS";

export const RESOLVE_DOUBT2_REQUEST = "RESOLVE_DOUBT2_REQUEST";
export const RESOLVE_DOUBT2_ERROR = "RESOLVE_DOUBT2_ERROR";
export const RESOLVE_DOUBT2_SUCCESS = "RESOLVE_DOUBT2_SUCCESS";

export const ADD_DOUBT2_RESPONSE_REQUEST = "ADD_DOUBT2_RESPONSE_REQUEST";
export const ADD_DOUBT2_RESPONSE_ERROR = "ADD_DOUBT2_RESPONSE_ERROR";
export const ADD_DOUBT2_RESPONSE_SUCCESS = "ADD_DOUBT2_RESPONSE_SUCCESS";
