export const CREATE_DOUBT3_REQUEST = "CREATE_DOUBT3_REQUEST";
export const CREATE_DOUBT3_ERROR = "CREATE_DOUBT3_ERROR";
export const CREATE_DOUBT3_SUCCESS = "CREATE_DOUBT3_SUCCESS";

export const GET_DOUBT3_REQUEST = "GET_DOUBT3_REQUEST";
export const GET_DOUBT3_ERROR = "GET_DOUBT3_ERROR";
export const GET_DOUBT3_SUCCESS = "GET_DOUBT3_SUCCESS";

export const GET_SINGLE_DOUBT3_REQUEST = "GET_SINGLE_DOUBT3_REQUEST";
export const GET_SINGLE_DOUBT3_ERROR = "GET_SINGLE_DOUBT3_ERROR";
export const GET_SINGLE_DOUBT3_SUCCESS = "GET_SINGLE_DOUBT3_SUCCESS";

export const DELETE_DOUBT3_REQUEST = "DELETE_DOUBT3_REQUEST";
export const DELETE_DOUBT3_ERROR = "DELETE_DOUBT3_ERROR";
export const DELETE_DOUBT3_SUCCESS = "DELETE_DOUBT3_SUCCESS";

export const RESOLVE_DOUBT3_REQUEST = "RESOLVE_DOUBT3_REQUEST";
export const RESOLVE_DOUBT3_ERROR = "RESOLVE_DOUBT3_ERROR";
export const RESOLVE_DOUBT3_SUCCESS = "RESOLVE_DOUBT3_SUCCESS";

export const ADD_DOUBT3_RESPONSE_REQUEST = "ADD_DOUBT3_RESPONSE_REQUEST";
export const ADD_DOUBT3_RESPONSE_ERROR = "ADD_DOUBT3_RESPONSE_ERROR";
export const ADD_DOUBT3_RESPONSE_SUCCESS = "ADD_DOUBT3_RESPONSE_SUCCESS";
