export const CREATE_SCRATCH2_REQUEST = "CREATE_SCRATCH2_REQUEST";
export const CREATE_SCRATCH2_ERROR = "CREATE_SCRATCH2_ERROR";
export const CREATE_SCRATCH2_SUCCESS = "CREATE_SCRATCH2_SUCCESS";

export const GET_SCRATCH2_REQUEST = "GET_SCRATCH2_REQUEST";
export const GET_SCRATCH2_ERROR = "GET_SCRATCH2_ERROR";
export const GET_SCRATCH2_SUCCESS = "GET_SCRATCH2_SUCCESS";

export const DELETE_SCRATCH2_REQUEST = "DELETE_SCRATCH2_REQUEST";
export const DELETE_SCRATCH2_ERROR = "DELETE_SCRATCH2_ERROR";
export const DELETE_SCRATCH2_SUCCESS = "DELETE_SCRATCH2_SUCCESS";

export const GET_SINGLE_SCRATCH2_REQUEST = "GET_SINGLE_SCRATCH2_REQUEST";
export const GET_SINGLE_SCRATCH2_ERROR = "GET_SINGLE_SCRATCH2_ERROR";
export const GET_SINGLE_SCRATCH2_SUCCESS = "GET_SINGLE_SCRATCH2_SUCCESS";

export const ADD_SCRATCH2_RESPONSE_REQUEST = "ADD_SCRATCH2__RESPONSE_REQUEST";
export const ADD_SCRATCH2__RESPONSE_ERROR = "ADD_SCRATCH2__RESPONSE_ERROR";
export const ADD_SCRATCH2__RESPONSE_SUCCESS = "ADD_SCRATCH2__RESPONSE_SUCCESS";