export const CREATE_SCRATCH3_REQUEST = "CREATE_SCRATCH3_REQUEST";
export const CREATE_SCRATCH3_ERROR = "CREATE_SCRATCH3_ERROR";
export const CREATE_SCRATCH3_SUCCESS = "CREATE_SCRATCH3_SUCCESS";

export const GET_SCRATCH3_REQUEST = "GET_SCRATCH3_REQUEST";
export const GET_SCRATCH3_ERROR = "GET_SCRATCH3_ERROR";
export const GET_SCRATCH3_SUCCESS = "GET_SCRATCH3_SUCCESS";

export const DELETE_SCRATCH3_REQUEST = "DELETE_SCRATCH3_REQUEST";
export const DELETE_SCRATCH3_ERROR = "DELETE_SCRATCH3_ERROR";
export const DELETE_SCRATCH3_SUCCESS = "DELETE_SCRATCH3_SUCCESS";

export const GET_SINGLE_SCRATCH3_REQUEST = "GET_SINGLE_SCRATCH3_REQUEST";
export const GET_SINGLE_SCRATCH3_ERROR = "GET_SINGLE_SCRATCH3_ERROR";
export const GET_SINGLE_SCRATCH3_SUCCESS = "GET_SINGLE_SCRATCH3_SUCCESS";

export const ADD_SCRATCH3_RESPONSE_REQUEST = "ADD_SCRATCH3__RESPONSE_REQUEST";
export const ADD_SCRATCH3__RESPONSE_ERROR = "ADD_SCRATCH3__RESPONSE_ERROR";
export const ADD_SCRATCH3__RESPONSE_SUCCESS = "ADD_SCRATCH3__RESPONSE_SUCCESS";